version: "3.9"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - net
  postgres:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - net
  app:
    container_name: app
    image: ${ORGANIZATION}/${PROJECT_NAME}:${PROJECT_VERSION}
    env_file:
      - ./.env
    ports:
      - "8080:${HTTP_PORT}"
      - "8443:${HTTPS_PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - net
volumes:
  postgres:
networks:
  net:
    name: ${PROJECT_NAME}